name: kagekagetetris
version: git
summary: The OSS game like Tetris!
description: |
  It is the game like Tetris felt Kage!
confinement: devmode
base: core18
parts:
  test-httplab:
    plugin: go
    go-importpath: github.com/PenguinCabinet/kagekage_Tetris
    source: .
    source-type: git
    build-packages:
      - gcc
apps:
  kagekagetetris:
    command: kagekagetetris