name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

env:
  ITCH_USERNAME: penguincabinet
  ITCH_GAME_ID: kagekage_Block
jobs:
  goreleaser-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Install Library
        run: |
          sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r"
          sudo apt-get install -y  libc6-dev libglu1-mesa-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config crossbuild-essential-arm64 gcc-arm-linux-gnueabi g++-arm-linux-gnueabi clang-12 gcc-arm-linux-gnueabihf --install-suggests
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist --config=.goreleaser_linux.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  goreleaser-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist --config=.goreleaser_windows.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  goreleaser-mac:
    runs-on: macos-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Install GoReleaser
        run: brew install goreleaser
      - name: Run GoReleaser
        run: goreleaser release --rm-dist --config=.goreleaser_darwin.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: Upload to Itch
    runs-on: ubuntu-latest
    needs: [goreleaser-linux, goreleaser-windows, goreleaser-mac]
    strategy:
      fail-fast: true
      matrix:
        channel:
          - windows
          - darwin
          - linux
    steps:
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'penguincabinet/kagekage_Block'
          version: 'tags/${{ github.ref }}'
          file: 'kagekage_Block_${{ matrix.channel }}_x86_64.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: kagekage_Block_${{ matrix.channel }}_x86_64.zip
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
          buildNumber: ${{ github.ref }}
